#
# Project NuriKit - Copyright 2024 SNU Compbio Lab.
# SPDX-License-Identifier: Apache-2.0
#

name: nurikit-docs
channels:
  - conda-forge
dependencies:
  - python=3.12
  - cmake>=3.16
  - libboost-devel>=1.82
  - libabseil>=20240116.0
  - eigen>=3.4,<5.0
  - spectralib>=1.0
  - pybind11>=2.13,<3.0
  - pip
